FROM ubuntu:20.04
RUN apt-get update
RUN apt-get install -y python3 python3-pip
RUN pip3 install easydict 
RUN pip3 install numpy 
RUN pip3 install torch
RUN pip3 install torch  --upgrade
RUN pip3 install numpy  --upgrade
